### ISSUE TITLE
Cannot find module 'nestjs-rollbar'

### ISSUE THREAD

**Issue by pqr** [AlariCode/nestjs-rollbar#1]
Installed with `yarn add nestjs-rollbar` - installation successful.

Then in app.module.ts I do import:
```
import { LoggerModule } from 'nestjs-rollbar';
```

When I start compilation by standard nest scripts (like `yarn build` or `yarn start:dev`) I get an error:
```
src/app.module.ts(14,30): error TS2307: Cannot find module 'nestjs-rollbar'.
```

Checked my `node_modules` dir - there is a `nestjs-rollbar` dir, but what is suspicious - there is no `dist` inside `nestjs-rollbar`, but `node_modules/nestjs-rollbar/package.json` referees to ` "main": "./dist/index.js"`

**Comment by AlariCode** [comment]
Thanks, I’ll investigate this bug tomorrow, and give you a feedback.

**Comment by AlariCode** [comment]
@pqr, I updated library and fixed your issue. You should update to version 1.0.1. Thanks for bug report!
