### ISSUE TITLE
Error of "...has no exported member 'RollbarInjection'" after upgrade to newest version

### ISSUE THREAD

**Issue by arcticwind9653** [AlariCode/nestjs-rollbar#2]
Hi,

As the title suggested. After updating to the newest version, I am getting such error.

Is there a new way to use RollbarInjection?

cheers,
Thomas

**Comment by AlariCode** [comment]
@arcticwind9653  Sorry for breaking changes!(
Now there is no need for RollbarInjection anymore.
To use RollbarLogger in any service or controller just inject it in constructor:

```javascript
import { RollbarLogger } from 'nestjs-rollbar';

constructor(
		private readonly rollbarLogger: RollbarLogger
	) {}
```

Thanks you for your feedback! I updated docs.

**Comment by AlariCode** [comment]
@arcticwind9653 closing issue. If you have any questions or error, please let me know.
