### ISSUE TITLE
Upgrade nestjs dependencies to ^10.x.x

### ISSUE THREAD

**Issue by marlon-chagas** [AlariCode/nestjs-rollbar#21]
While upgrading to nestjs@10 I faced the following issue:

![image](https://github.com/AlariCode/nestjs-rollbar/assets/120677604/09e013ea-1ee9-4fbe-ae5c-7b20abe7b22b)

Can I create an PR with this bump in `nestjs-rollbar` lib?

**Comment by kevin-riquena** [comment]
+1

**Comment by marlon-chagas** [comment]
I have created this pull request: https://github.com/AlariCode/nestjs-rollbar/pull/22

**Comment by AlariCode** [comment]
Released in 2.0.1
