### ISSUE TITLE
Enabled flag

### ISSUE THREAD

**Issue by sophieheb** [AlariCode/nestjs-rollbar#3]
We would like to be able to turn the logger on in production but off in test & dev.

It would be great to have an enabled flag in place in the initial config so we could achieve this.

Happy to submit a PR.

**Comment by AlariCode** [comment]
It would be great, if you submit a PR!

**Comment by rhutchison** [comment]
@sophieheb can't you just set enabled: false on the rollbar config?

**Comment by rhutchison** [comment]
@sophieheb I didn't realize it was overriding the rollbar config.  I sent a PR.

**Comment by AlariCode** [comment]
Flag added with merge request. #4
