### ISSUE TITLE
 Class 'RollbarLogger' incorrectly imp lements interface 'LoggerService'

### ISSUE THREAD

**Issue by ghost** [AlariCode/nestjs-rollbar#6]
![image](https://user-images.githubusercontent.com/43011265/90312569-3631f000-df0e-11ea-9a4a-48ddca92eece.png)

**Comment by jits** [comment]
Seeing this too with the latest `1.4.0` version.

**Comment by maxdimaz** [comment]
any update on this issue? I just got this issue on 1 of 7 project
