### ISSUE TITLE
Property 'error' does not exist on type 'RollbarLogger'.

### ISSUE THREAD

**Issue by ganeshmani** [AlariCode/nestjs-rollbar#9]
I am trying to use RollbarLogger inside catch. but, it fails with 

`Property 'error' does not exist on type 'RollbarLogger'.`

`catch (err) {
      this.rollbarLogger.error(err, 'Error')
      throw err;
 }`

Version:
`"nestjs-rollbar": "1.7.0"`

Am I missing anything here?

**Comment by ganeshmani** [comment]
I think this is because of types in nestjs-rollbar. Here,
```
import Rollbar from 'rollbar';
```

If I change this back to 
```
import * as Rollbar from 'rollbar';
```
It's not showing me this error. 

Ref: https://github.com/AlariCode/nestjs-rollbar/pull/8

**Comment by tkssharma** [comment]
`import * as Rollbar from 'rollbar';

will work 
`
